### ISSUE TITLE
How it's all connected?

### ISSUE THREAD

**Issue by szymonprz** [Gaudon/zephyr-cycling#21]
Hi @Gaudon this project looks great! My brother found it while searching for something to control his fan during cycling and it looks promising, is there any chance that you could post some pictures or schemas of how this hardware is connected?

**Comment by Gaudon** [comment]
Hmm it's not going to be super useful since this configuration will vary fan to fan. There certainly is a degree of electrical understanding a person would need to have to make use of this project in anyway. 

With that being said, at a high level it's connected and setup in the following way.

- Configure the IO pins in the configuration file based on the GPIO pins you want to use to turn on and off each relay (each fan mode)
- Splice your fans power lines (ie: 120V) into each relay with the power out of the relay going back to each fan modes power line. 
- Using the relay board (or a similar one) as listed in the description, you can dictate which relay is outputting power to the fan.

In general, this works when you have a fan that operates with a physical hardware switch that essentially sends power to individual circuits that go to the motor. Quite common in home fans with 1-6 modes of operation (3 in my case).

Here are some generic shots of the circuit/setup I use for my fan under my cycling table. I never did pursue getting a PCB made or making an enclosure heh.

![fan1](https://github.com/user-attachments/assets/8f2c9136-1561-41da-bb81-a36a4dfcd1fb)
![fan2](https://github.com/user-attachments/assets/2840f0ce-ee4b-4acf-bd11-11d99b5be520)
![fan3](https://github.com/user-attachments/assets/53c5d03c-9406-4452-8f6c-dfcb36695fb9)

**Comment by szymonprz** [comment]
Thanks a lot for this! This is super useful. One more question that we have, how is the second picow connected in this setup (the one that simulates heart rate monitor if I understand correctly)

**Comment by Gaudon** [comment]
> Thanks a lot for this! This is super useful. One more question that we have, how is the second picow connected in this setup (the one that simulates heart rate monitor if I understand correctly)

Neither of the PicoW's simulate a heart rate monitor but instead they *proxy* a heart rate monitor. 

If you have a modern heart rate sensor this is probably not required as they can often pair with multiple connections simultaneously. I use a Wahoo Tickr and mine can pair both with my fan and Zwift at the same time.

However, if yours cannot you would need to install a second pico running the software in secondary mode (config file) that will enable the uart RX functionally as well as the Bluetooth heartrate functionality.

The second and first Pico are connected via gpio pins in the UART block of pins (see picoW Pinot diagram) such that TX on the primary goes to RX on the secondary and vice versa.

With the software configured you should be able to pair your heart rate sensor and see the data show up as a secondary heart rate sensor called "Zephyr HRM" in zwift or other software.
